### PR TITLE
use config.validator instead of validator

### PR DESCRIPTION
**Pull request by seiyria**
this allows you to actually specify a custom validator instead of having to patch node-validator.

### CODE REVIEW

**Comment by seiyria** [comment]
thanks. can you let me know when this is published?

**Comment by kripod** [comment]
@seiyria It's been published in v2.0.2 😊

**Comment by seiyria** [comment]
thanks so much!

**Comment by seiyria** [comment]
Strangely, I keep getting an error trying to install 2.0.2:

npm ERR! enoent ENOENT: no such file or directory, open '/Users/seiyria/GitHub/posys/node_modules/.staging/bookshelf-validate-d0eadb27/package.json'

edit, here's a log where you can see the problem: https://travis-ci.org/seiyria/posys/jobs/182130557#L2395

**Comment by seiyria** [comment]
@kripod could you please re-publish as 2.0.3 or something? I cannot install 2.0.2 and it's breaking my builds + forcing me to keep local changes for this. Thanks!

**Comment by kripod** [comment]
@seiyria I just re-published the package as v2.0.3 with updated dependencies. Sorry for the inconvenience!

**Comment by seiyria** [comment]
Thanks! Looks like it's working now.

**Pull request merged**
